name: CI for @antonytm/clixml-parser
on:
    push:
      branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        working-directory: .
        run: npm install
      - name: Build package
        working-directory: .
        run: npm run build
      - name: Run tests
        working-directory: .
        run: npm run test